### ISSUE TITLE
Enhance configuration documentation with configuration of mopidy

### ISSUE THREAD

**Issue by ibex-are-goats** [mopidy/mopidy-alsamixer#25]
I see what should be in the alsamixer config, but I'm not sure what to put in the mopidy config. For example:

[audio]
mixer = software
mixer_volume =
output = autoaudiosink
buffer_time =

**Comment by kingosticks** [comment]
The following should do it. I think you've made a good point, we should include this snippet in the readme:

```
[audio]
mixer = alsamixer
```
