### ISSUE TITLE
USB/DAC Device without mixer controls

### ISSUE THREAD

**Issue by Apieceofbluesky** [mopidy/mopidy-alsamixer#4]
Hi, 

i was struggling to set up my Teac AH-01 (Amp with async usb dac), because it offered no mixer controls. Mopidy wouldn´t start with PCM or Master Setting. I could only work around it, to set the alsamixer to the internal soundcard of my raspberry pi (0), while specifying the Teac as alsasink output device. 

software mixer would work as well of course, but with significantly inferior sound quality.

Not a big issue, but maybe would help others setting it up...Thx!

**Comment by jodal** [comment]
In Mopidy, mixer and output is not the same. Mixer only adjusts the volume, while the output decides what sound card you use. There's no problem using `audio/output=alsasink` and `audio/mixer=software` in combination. `alsasink` doesn't require `alsamixer` to be used.

Not sure if there's anything actionable here. Feel free to close unless you have any suggestions for improvements.

**Comment by Apieceofbluesky** [comment]
When i did use your suggested combination at first, i noticed significant loss of audio quality, with "hearable" jitter and even the occasional pop on the rpi. The CPU load on mopidy seemed to be lower compared to use of alsamixer.

The solution i use now has perfect audio quality, but of course the volume control in the web frontends doesn´t work, not that would i need / want it. 

My suggestion would be, to adjust the alsamixer in a way, that it would work on DACs that don´t offer any mixer controls, with the sole purpose of having an easier setup. Right now, you have to work around a bit to have optimum audio, with assigning the alsamixer to another soundcard, order for mopidy to boot up.

**Comment by jodal** [comment]
Sounds like what you really want is to be able to turn off volume mixing in Mopidy entirely. That will hopefully be implemented in Mopidy 0.20, ref. mopidy/mopidy#936.

Mopidy-ALSAMixer is not the right place to make it possible to disable volume mixing through Mopidy.

Would this be a good solution for you?

**Comment by Apieceofbluesky** [comment]
Yes, awesome, that would be absolutely perfect, and would make it easier to set up for new users. Thanks, have a good day!
