### ISSUE TITLE
Bug with disabled on-board audio using an external sound card

### ISSUE THREAD

**Issue by perplexa** [mopidy/mopidy-alsamixer#8]
Hey,

I have been experiencing a bug with mopidy-alsamixer that occurs when you disable the onboard audio device on a raspberrypi.

The issue is in [mixer.py](https://github.com/mopidy/mopidy-alsamixer/blob/master/mopidy_alsamixer/mixer.py#L27-L36), which assumes that audio devices start at 0. However, my external sound devicee gets ID 1, thus assuming IDs start at 0 breaks the mixer.

```
Sep 23 14:54:21 arcam mopidy[2684]: ERROR    Mixer (AlsaMixer) initialization error: Could not find ALSA soundcard with index 1. Known soundcards include: 0 (DragonFly)
```

The list of my audio devices looks like:

```
$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: DragonFly [AudioQuest DragonFly], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Setting `alsamixer/card = 0` would bypass mopidy-alsamixer's check completely and cause an ALSAAudioError as the ID is not actually present.

For now I commented out the marked lines in mixer.py (see above) to allow me to use `card = 1` without having two cards in the system and everything is working as intended.

**Comment by jodal** [comment]
@perplexa I believe your issue was fixed by commit e05571590545f533a781e41e1fee507a6b09eefa. If you can test it and confirm, I'll roll a new release for you.
